# Generated by Django 3.2.20 on 2023-07-19 13:28

from django.db import migrations, models

import core.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="This is your in-game display name. Letters, spaces, digits and @/./+/-/_ ok. 150 chr max.",
                max_length=150,
                null=True,
                validators=[core.models.user.UserNameValidator()],
                verbose_name="Display Name",
            ),
        ),
    ]
