# Generated by Django 3.2.20 on 2023-07-19 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesubmission",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.round",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
