# Generated by Django 3.2.20 on 2023-07-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def get_default():
    return "perchweb" if settings.ENV == "prod" else "test-game"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_gamesubmission_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="players",
        ),
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                default=get_default,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.game",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="players_temp",
            field=models.ManyToManyField(
                through="core.Player", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RenameField(
            model_name="game",
            old_name="players_temp",
            new_name="players",
        ),
    ]
