# Generated by Django 3.2.20 on 2023-07-22 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_many_to_many_through_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="games",
        ),
        migrations.DeleteModel(
            name="GameSubmission",
        ),
    ]
