# Generated by Django 3.2.20 on 2023-07-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20230722_0042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round",
                to="core.submission",
            ),
        ),
    ]
