name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: |
          pip
          pietry
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Delete static files
      run: |
        echo $(pwd)
        pwd
        ls
        rm -rf ./src/static/

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download environment artifacts
      uses: actions/download-artifact@v2
      with:
        name: environment
        path: |
          .
          ~/.cache/pypoetry/virtualenvs
    - name: Analyzing the code with pylint
      run: |
        poetry run pylint --load-plugins=pylint_django --django-settings-module=daily_groove.settings ./src
    - name: Analyzing code with black
      run: |
        poetry run black . --check

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run Unit Tests
      run: |
        poetry run pytest src
